name: "Building from scratch  podman CI workflow"


on:
  push:
    branches: [ test ]


jobs:

  podman-ubuntu-1804-job:
    name: "Building from scratch podman testing on ubuntu-18.04"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  
    - name: "Build and Run Dependencies "
      run: |
        # Unable to locate package libbtrfs-dev
        echo "deb http://us.archive.ubuntu.com/ubuntu/ xenial main universe" |sudo tee -a /etc/apt/sources.list
        echo "deb-src http://us.archive.ubuntu.com/ubuntu/ xenial main universe" |sudo tee -a /etc/apt/sources.list
        sudo apt-get update -y && sudo apt-get install libesd0-dev -y
        # https://podman.io/getting-started/installation
        sudo apt-get update -y
        sudo apt-get install \
          btrfs-progs \
          git \
          golang-go \
          go-md2man \
          iptables \
          libassuan-dev \
          libbtrfs-dev \
          libc6-dev \
          libdevmapper-dev \
          libglib2.0-dev \
          libgpgme-dev \
          libgpg-error-dev \
          libprotobuf-dev \
          libprotobuf-c-dev \
          libseccomp-dev \
          libselinux1-dev \
          libsystemd-dev \
          pkg-config \
          runc \
          uidmap
        # # Make sure that the Linux kernel supports user namespaces
        # zgrep CONFIG_USER_NS /proc/config.gz
     


